spring.application.name=SpringSecEx

spring.security.user.name=adi
spring.security.user.password=welcome

spring.datasource.url=jdbc:postgresql://localhost:5432/loginDetails
spring.datasource.username=postgres
spring.datasource.password=welcome